const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  minimize: () => ipcRenderer.send('minimize'),
  maximize: () => ipcRenderer.send('maximize'),
  close: () => ipcRenderer.send('close'),
  onWindowStateChange: (callback) => ipcRenderer.on('window-state', (_, isMaximized) => callback(isMaximized)),
  startFileDrag: (filePath) => ipcRenderer.send('start-drag', filePath),
  openDirectory: () => ipcRenderer.invoke('dialog:openDirectory'),
  toggleDevTools: () => ipcRenderer.send('toggle-devtools'),
  saveDirectory: (data) => ipcRenderer.invoke('save-directory', data),
  getDirectory: () => ipcRenderer.invoke('get-directory'),
  getSymphonyFiles: (directoryPath) => ipcRenderer.invoke('get-symphony-files', directoryPath),
  runPythonScript: (args) => ipcRenderer.invoke('run-python-script', args),
  renameFile: (filePath, newName) => ipcRenderer.invoke('rename-file', { filePath, newName }),
  getMetadata: (filePath) => ipcRenderer.invoke('get-metadata', filePath),
  setMetadata: (filePath, metadata) => ipcRenderer.invoke('set-metadata', { filePath, metadata }),
  copyFile: (src, dest) => ipcRenderer.invoke('copy-file', src, dest),
  fileExists: (filePath) => ipcRenderer.invoke('file-exists', filePath),
  deleteFile: (filePath) => ipcRenderer.invoke('delete-file', filePath),
  getRecentlyViewed: () => ipcRenderer.invoke('get-recently-viewed'),
  openFileLocation: (filePath) => ipcRenderer.invoke('open-file-location', filePath),
  removeDirectory: (section, dirName) => ipcRenderer.invoke('remove-directory', section, dirName),
  runPythonRetrieve: (filePath) => ipcRenderer.invoke('run-python-retrieve', filePath),
  checkIfExists: (data) => ipcRenderer.invoke('check-if-exists', data),
  recentlyViewedDelete: (fileName) => ipcRenderer.invoke('recently-viewed-delete', fileName),
  getSectionForPath: (filePath) => ipcRenderer.invoke('get-section-for-path', filePath),
  openNativeApp: (filePath) => ipcRenderer.invoke('open-native-app', filePath),
  getStars: () => ipcRenderer.invoke('get-stars'),
  addStar: (filePath) => ipcRenderer.invoke('add-star', filePath),
  removeStar: (filePath) => ipcRenderer.invoke('remove-star', filePath),
  moveFileRaw: (fileBuffer, fileName, destinationDir) => ipcRenderer.invoke('move-file-raw', fileBuffer, fileName, destinationDir),
  getUserSettings: () => ipcRenderer.invoke('get-user-settings'),
  updateUserSettings: (key, value) => ipcRenderer.invoke('update-user-settings', key, value),
  openExternal: (url) => ipcRenderer.send('open-external', url)
});