on:
  push:
    branches:
    - release-mac
    - release-win64

jobs:
  build-mac:
    name: Build on macOS
    if: github.ref == 'refs/heads/release-mac'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    - name: Package app for Mac
      run: npm run package-app:mac
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-mac
        path: dist/

  build-windows:
    name: Build on Windows
    if: github.ref == 'refs/heads/release-win64'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    - name: Package app for Windows
      run: npm run package-app:windows
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-windows
        path: dist/